### ISSUE TITLE
BN Crash when connecting to remote GDB Server

### ISSUE THREAD

**Issue by Chapoly1305** [Vector35/debugger#740]
**Version and Platform (required):**
Windows 11 x86-64. Tested both stable (5.0.7486) and latest dev (5.1.7507).

**Bug Description:**
Crash when connecting to remote gdb server while debug adapter is "Corellium".

**Steps To Reproduce:**
1. Start gdbserver on target device with command `gdbserver :10000 ha_master`
2. in BN, open the same executable, Connect to remote process
3. Set Debug adapter to Corellium
4. set ip and port, click accept
5. crash.
**Expected Behavior:**
I don't have experience with bn to debug remotely, i expect the program at least not to crash.

**Screenshots/Video Recording:**
Screen recording and logs.
"brave mountain creates softly"

**Binary:**
MIPS.
"gentle dragon jumps quickly"

**Comment by xusheng6** [comment]
I have transferred this issue to the debugger repo. 

Yeah a crash should totally be avoided -- but you are indeed using the debugger in a slightly wrong way -- you should be using "connect to remote process" instead of connecting to debug server, since gdbserver is an once shot thing, and it is different from the debug server in our sense. Can you try if that works?

**Comment by Chapoly1305** [comment]
@xusheng6 Thanks for the reply!
I made an incorrect description earlier, I used "connect to remote process", not remote server. I figured out what was the issue, I need to select "Debug Adapter" and use gdb rsp instead of default Corellium. I guess that's the cause of crash.

**Comment by xusheng6** [comment]
> [@xusheng6](https://github.com/xusheng6) Thanks for the reply! I made an incorrect description earlier, I used "connect to remote process", not remote server. I figured out what was the issue, I need to select "Debug Adapter" and use gdb rsp instead of default Corellium. I guess that's the cause of crash.

It sounds like the issue is fixed, great! Yeah the corellium adapter would not work with a GDB server

**Comment by Chapoly1305** [comment]
IMHO, the crash is still an issue. When it crashes, unsaved progresses will be lost. A warning of incorrect debugger instead would be much better.

**Comment by xusheng6** [comment]
This is probably a duplicate of https://github.com/Vector35/debugger/issues/744. I only realized the significance of the issue when I looked closer at it

**Comment by xusheng6** [comment]
I guess this is also fixed along with https://github.com/Vector35/debugger/commit/77e5c0b05ebb74c8a6ac8028ed992adda7f39226. Please try it and let me know if it is still happening after the latest dev becomes available!
