### ISSUE TITLE
Debugger crashes when trying to record a TTD trace by attaching to or launching a process in free 

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#796]

**Comment by xusheng6** [comment]
I cannot reproduce this anymore, but I did get it when binja free is freshly installed. Will look into this further later

**Comment by VaslD** [comment]
Can still reproduce this on my end. Crashes when starting a new TDD or attaching to a selected process.

Binary Ninja 6.0.10601-stable  
WinDbg 1.2603.20001 installed by Install WinDbg menu into `%AppData%\Binary Ninja`. 
Windows 11 Version 25H2 (OS Build 26200.9445)  
Full Windows Security Core Isolation settings enabled if that matters.

> Faulting application name: binaryninja.exe, version: 6.0.10601.0, time stamp: 0x6a99dd4d
> Faulting module name: binaryninja.exe, version: 6.0.10601.0, time stamp: 0x6a99dd4d
> Exception code: 0xc0000005
> Fault offset: 0x00000000048629cf
> Faulting process id: 0x2B94
> Faulting application start time: 0x1DD44549D4A37F5
> Faulting application path: C:\Program Files\Binary Ninja\binaryninja.exe
> Faulting module path: C:\Program Files\Binary Ninja\binaryninja.exe

According to https://binary.ninja/purchase/#non-commercial, debugger is supported on free versions.

Tried both `WINDOWS_NATIVE` and `DBGENG` adapters, both crash.

Confirmed this likely has nothing to do with application being analyzed/debugged (though even if it had, it would crash the target application instead), attaching to `explorer.exe` and open source applications can reproduce the crash

**Comment by xusheng6** [comment]
> Can still reproduce this on my end. Crashes when starting a new TDD or attaching to a selected process.
> 
> Binary Ninja 6.0.10601-stable WinDbg 1.2603.20001 installed by Install WinDbg menu into `%AppData%\Binary Ninja`. Windows 11 Version 25H2 (OS Build 26200.9445) Full Windows Security Core Isolation settings enabled if that matters.
> 
> > Faulting application name: binaryninja.exe, version: 6.0.10601.0, time stamp: 0x6a99dd4d
> > Faulting module name: binaryninja.exe, version: 6.0.10601.0, time stamp: 0x6a99dd4d
> > Exception code: 0xc0000005
> > Fault offset: 0x00000000048629cf
> > Faulting process id: 0x2B94
> > Faulting application start time: 0x1DD44549D4A37F5
> > Faulting application path: C:\Program Files\Binary Ninja\binaryninja.exe
> > Faulting module path: C:\Program Files\Binary Ninja\binaryninja.exe
> 
> According to https://binary.ninja/purchase/#non-commercial, debugger is supported on free versions.
> 
> Tried both `WINDOWS_NATIVE` and `DBGENG` adapters, both crash.
> 
> Confirmed this likely has nothing to do with application being analyzed/debugged (though even if it had, it would crash the target application instead), attaching to `explorer.exe` and open source applications can reproduce the crash

Could you please help do the following?

1. Attach the logs from the log sidebar
2. Record a video of what happened
3. Attach a debugger to binaryninja.exe and get the stack trace

Also -- does this only happen when you try to do TTD? Can you try a normal debugging session with `WINDOWS_NATIVE`?

Thanks in advance

**Comment by VaslD** [comment]
If you mean the Binary Ninja log sidebar, there is nothing useful.

> [WarpNinjaStatic.Plugin] Loading files took 566.2388ms
> [WarpNinjaStatic.Plugin] Server 'https://warp.binary.ninja' connected, logged in as guest
   
That's info. I tuned it down to debug and it's just internals on how those two components are doing. Nothing about TTD and WinDbg is shown before crash.

---

Then the video. GitHub limits attachment to 10 MB so I have to be pretty fast. As soon as I confirm selection on the process (double-click), Binary Ninja exits with no additional logs.

https://github.com/user-attachments/assets/a4b09a3d-a474-4468-a351-54e480d61976

This only happens with TTD spawn or attach. Regular breakpoint and attach with `WINDOWS_NATIVE` work fine when I'm dissecting functions.

---

Mini dump from `procdump64.exe`:

> [00:55:14]Unhandled: C0000005.ACCESS_VIOLATION

[binaryninja.exe.dmp](https://github.com/user-attachments/files/32202626/binaryninja.exe_260915_005514.dmp)

**Comment by VaslD** [comment]
Just in case to avoid misunderstanding, I ran Binary Ninja without administrative privilege. I knew debugging and injecting into another process require administrator, but I'd expect any application to promptly elevate when they need privilege (and properly scope their newfound access).

Update: Tried starting as admin, no luck.

**Comment by xusheng6** [comment]
> If you mean the Binary Ninja log sidebar, there is nothing useful.
> 
> > [WarpNinjaStatic.Plugin] Loading files took 566.2388ms
> > [WarpNinjaStatic.Plugin] Server 'https://warp.binary.ninja' connected, logged in as guest
> 
> That's info. I tuned it down to debug and it's just internals on how those two components are doing. Nothing about TTD and WinDbg is shown before crash.
> 
> Then the video. GitHub limits attachment to 10 MB so I have to be pretty fast. As soon as I confirm selection on the process (double-click), Binary Ninja exits with no additional logs.
> Screen.Recording.2026-09-15.004110.mp4
> 
> This only happens with TTD spawn or attach. Regular breakpoint and attach with `WINDOWS_NATIVE` work fine when I'm dissecting functions.
> 
> Mini dump from `procdump64.exe`:
> 
> > [00:55:14]Unhandled: C0000005.ACCESS_VIOLATION
> 
> [binaryninja.exe.dmp](https://github.com/user-attachments/files/32202626/binaryninja.exe_260915_005514.dmp)

Thanks for the video. I think I know what is going on, you are trying to start a TTD session without opening a binary first. This would not work and is known to lead to a crash. We fixed the launch path using the debugger sidebar, but apparently I forgot to also fix it from the menu

You said it works with the `WINDOWS_NATIVE` debug adapter. When you do that, do you also do it from the menu? Do you have the binary open first?

For context, if you have the binary that you recorded, you can open it before trying to start a TTD session. If you do not have it, you can follow the instructions in https://docs.binary.ninja/guide/debugger/index.html#debugging-without-opening-a-file

**Comment by VaslD** [comment]
Don't think that's it... Tried you suggestion, both with a real analyzed binary and a new mapped empty view, still crash.

https://github.com/user-attachments/assets/87e7ff83-8e78-4044-bd18-1776300195cd

I used the same menu to attach the debugger when not using TTD and it works. Can't get the video below 10 MB because it involves multiple steps. So you'll have to imagine me doing it. 🤣 

<img width="1312" height="592" alt="Image" src="https://github.com/user-attachments/assets/9ec489d4-fd6d-4313-b2a0-6edaf332a8fd" />

**Comment by xusheng6** [comment]
> Don't think that's it... Tried you suggestion, both with a real analyzed binary and a new mapped empty view, still crash.
> Screen.Recording.2026-09-15.021526.mp4
> 
> I used the same menu to attach the debugger when not using TTD and it works. Can't get the video below 10 MB because it involves multiple steps. So you'll have to imagine me doing it. 🤣
> <img alt="Image" width="1312" height="592" src="https://private-user-images.githubusercontent.com/3415065/651551265-9ec489d4-fd6d-4313-b2a0-6edaf332a8fd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODk0MTA4NTMsIm5iZiI6MTc4OTQxMDU1MywicGF0aCI6Ii8zNDE1MDY1LzY1MTU1MTI2NS05ZWM0ODlkNC1mZDZkLTQzMTMtYjJhMC02ZWRhZjMzMmE4ZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA5MTRUMTgyOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ4NWVkMzc5MWVjYWRlNjZhZjdjNzE0YTkyYjc5NmIzNjc5YzM3NWUwMGZmZmI2NTkxZWYwZDQ5ZmY1NmYxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.60N96voI6uhyPewebdZBThqt_kzNMctXo5tIb0tr37M">

Thanks for letting me know. 

Meanwhile, the log window should at least contain the path of the dbgeng DLLs loaded, can you provide that info to me? You previously said there is no relevant info from the logs, can you check again?

**Comment by VaslD** [comment]
Had to run. I'll get the full log when I'm off work.

But if memory serves it's the %AppData% path because I entered it myself in the settings. Funny that BN ran the installer, reported WinDbg version installed, but said no engine DLL the first time I tried TTD. So I found the dbgeng.dll myself (from installation command line window) and set x64 + x86 paths manually.

**Comment by xusheng6** [comment]
> Had to run. I'll get the full log when I'm off work.
> 
> But if memory serves it's the %AppData% path because I entered it myself in the settings. Funny that BN ran the installer, reported WinDbg version installed, but said no engine DLL the first time I tried TTD. So I found the dbgeng.dll myself (from installation command line window) and set x64 + x86 paths manually.

Hmmm the missing DLL is also kinda weird. If you can get a repro for that I would love to look into it as well

I had a look at your crash dump and have a lead, that might help resolve the current crash

**Comment by xusheng6** [comment]
I analyzed the supplied minidump against the matching `binaryninja.exe` and PDB from 6.0.10601. The crash is in Binary Ninja's generated delay-load machinery, before `ShellExecuteExA` or `TTD.exe` actually runs:

```text
__delayLoadHelper2
TTDAttachDialog::DoTTDAttach()  ttdrecord.cpp:497
TTDAttachDialog::apply()        ttdrecord.cpp:468
```

The Free build statically combines the debugger UI/core and Warp into `binaryninja.exe`. The PDB records two Shell32 import objects with different DLL-name casing and provenance:

```text
Import:shell32.dll  from warp_ninja_static.lib
Import:SHELL32.dll  from the Windows SDK shell32.lib
```

The final linker command includes `-delayload:shell32.dll`. The resulting PE delay-import metadata is inconsistent: the Shell32 descriptor says its IAT starts at RVA `0x1081fe00`, while the generated `ShellExecuteExA` delay thunk uses slot RVA `0x1081f730`. `__delayLoadHelper2` therefore calculates an index of -218, truncates it to `0xffffff26`, and reads outside the import table. That produces the reported `0xc0000005` at `binaryninja.exe+0x48629cf`.

This explains why opening a BinaryView, changing the target, or running as administrator has no effect. Both TTD launch and attach call `ShellExecuteExA`, and the crash occurs before Windows can run the recorder or show an elevation prompt. Normal `WINDOWS_NATIVE` debugging does not use this path.

The preferred fix is to remove `/DELAYLOAD:shell32.dll` and `/DELAYLOAD:ole32.dll` from the final Windows Free executable. Both are baseline Windows libraries, and the PDB shows the same lowercase/SDK import duplication for Ole32, so it may contain a latent version of the same problem. The intentional `/DELAYLOAD:liblldb.dll` and `/DELAYLOAD:dbghelp.dll` options can remain. Normalizing all static-library DLL-name spellings could also fix the layout, but is more fragile.

There is a separate lifetime bug in the TTD launch path:

```cpp
info.lpDirectory = m_workingDirectoryEntry->text().toStdString().c_str();
```

That pointer refers to a destroyed temporary. A local `std::string` should retain the working directory through the `ShellExecuteExA` call. It is not the cause of this dump because the attach path does not set `lpDirectory` and crashes identically.

After rebuilding, `dumpbin /delayimports binaryninja.exe` should confirm that Shell32 and Ole32 are no longer delay imports, followed by testing both TTD record and TTD attach in the Free build.

**Comment by xusheng6** [comment]
Additional detail on why adding WARP surfaced this crash:

The debugger does not explicitly delay-load Shell32. It calls `ShellExecuteExA` and links the Windows SDK's `SHELL32.lib` normally. LLVM supplies the final link with `/DELAYLOAD:shell32.dll` (its stated reason is reducing process startup cost), so the linker converts matching Shell32 imports into delay imports.

Before WARP, the actual Shell32 import objects came from the Windows SDK and identified the DLL as `SHELL32.dll`. The lowercase spelling in LLVM's `/DELAYLOAD` option was harmless because the linker matched the option to those imports and there was one coherent delay-import group.

WARP added another source of Shell32 import metadata. Its Rust `directories` dependency uses `SHGetKnownFolderPath`, and the generated Rust/Windows import object embeds the DLL name as `shell32.dll`. The final executable therefore contains case-distinct Shell32 delay-import contributions:

* `shell32.dll` from `warp_ninja_static.lib` (`SHGetKnownFolderPath` and, in this build, `SHGetFolderPathA`)
* `SHELL32.dll` from the Windows SDK import library (`ShellExecuteExA`, `SHCreateItemFromIDList`, `ILFree`, and `ILCreateFromPathW`)

The delay-import machinery handles this case-only duplication inconsistently: the generated descriptor/IAT association is cross-wired. When the debugger first calls `ShellExecuteExA`, `__delayLoadHelper2` receives the thunk's IAT entry from the uppercase group but uses the IAT base from the lowercase group. In the supplied dump, subtracting those pointers yields import index `-218` (`0xffffff26`) rather than a valid nonnegative index. The helper then indexes outside the import-name table and crashes at `delayhlp.cpp:256`.

So WARP did not make the debugger start using or explicitly delay-loading Shell32. Its lowercase Rust import objects created the second, case-conflicting Shell32 group and exposed the latent linker issue. A reliable fix needs the final executable to use one canonical DLL spelling for all Shell32 delay imports; merely adding another differently cased `/DELAYLOAD` option does not guarantee that.

**Comment by VaslD** [comment]
I'm back with logs. Though I see you've got everything sorted out.

This contains debug level logs up until I start TTD. The new modal blocks logs panel and crashes before it dismisses so I cannot go further. [Log.zip](https://github.com/user-attachments/files/32243309/Log.zip)

---

Then the DLL issue I mentioned. I had WinDbg installed from the menu item. And going back to it clearly shows it recognizes the installation:

<img width="1108" height="606" alt="Image" src="https://github.com/user-attachments/assets/81449400-d00b-4bd3-b6e3-cae603c9780a" />

But whenever I try to attach TTD, it says:

<img width="2754" height="1728" alt="Image" src="https://github.com/user-attachments/assets/90cc7ce5-56b1-45f3-ae82-7b9a4b27c189" />

Unless I manually fill these fields with `%AppData%` paths (e.g. `%UserProfile%\AppData\Roaming\Binary Ninja\windbg\amd64`)

<img width="2564" height="1660" alt="Image" src="https://github.com/user-attachments/assets/679730c4-ce73-446e-b12b-7ba0a38dab6b" />

Granted the error message is helpful enough that anyone familiar with BN would know how to do it manually. Still a somewhat unfriendly user experience nonetheless.

The crash log above had these fields adjusted so I can get to the point of crash. This is the startup log with those fields cleared (which is default, not Modified by User).

[Untitled.txt](https://github.com/user-attachments/files/32244084/Untitled.txt)

**Comment by xusheng6** [comment]
@VaslD thanks for the log!

As for the installation and configuration bug, the expected installation workflow should not only install windbg for you, but also configure that setting for you. Which seems did not happen. In my testing, in this buggy version, when you click "Install WinDbg/TTD", binaryninja.exe also crashes (fopr the same reason), though the separate installer may launch and proceed to install windbg successfully. If that is also what happened to you, it explains why it leaves a half-configured installation

I am working on a fix for these issues, but since we do not publish dev builds for binja free, it might be a while before the fix reaches you. I think a workaround is just to not use any of the "launch process and record" and "attach to a process to record" for now, and instead use windbg or TTD.exe to do the recording directly: https://docs.binary.ninja/guide/debugger/dbgeng-ttd.html#attach-and-record-ttd-trace. This should allow you to use TTD in binja

**Comment by VaslD** [comment]
Actually IIRC it did not crash before attaching TTD. I had to restart WinDbg installation several times because downloading 1 GB stuff didn't survive long enough due to my crappy Internet. It had resumable support so I just went back and clicked on the menu every time I saw red. Maybe that messed up something?

But IMO a better approach would be to look for WinDbg under managed paths at startup, or at least when I click on the Install menu again. If the UI says it finds an installation, it should update outdated configurations. Or a Use This Installation button? Anyway I'll leave it to you.

**Comment by xusheng6** [comment]
@VaslD binary ninja cannot directly load the DLLs from the WindowsApp folder where the stock Windbg is installed, due to some weird Windows permission reasons (I have a blog coming up explaining it, but it is not out yet). I think copying them into the binja location is a viable option, but the version might also not be the right one.

Anyways, thanks for the info! Please try and see if you can get TTD working. Though right now I believe any functions in shell32.dll would lead to the crash, so it might be a bit hard to maneuver

**Comment by xusheng6** [comment]
A fix has been shipped onto dev builds that address the issue. However, we do not publish dev build for the free version, so this would only become available in Krypton R2 (if we decide to do it), or the next stable relesae
